system:
    ip: 127.0.0.1
    port: 8082
    env: dev
mysql:
    host: 127.0.0.1
    port: 3306
    config: charset=utf8mb4&parseTime=True&loc=Local
    db: gvd_db
    username: remoteUser
    password: "12345678"
    logLevel: error
redis:
    ip: 127.0.0.1
    port: 6379
    password: "22331"
    poolSize: 100
es:
    addr: ""
    user: ""
    password: ""
jwt:
    expires: 8
    issuer: FightClub
    secret: uis&*jbb55dHRhf5
site:
    title: xx
    icon: dd
    abstract: ""
    iconHref: ""
    href: ""
    footer: ""
    content: ""
